[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "DB_PASSWORD"

[dev]
  publish = "public"

# Redirect all API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
